In [1]:
'''
1. Create a package named ‘cricket’ which will contain modules named
batsman and bowler. Create following functions in respective modules.
Import the package and call all these functions in your program
batsman: findaverage(runs,matches), strikerate(runs,balls)
bowler: findavg(runs,wickets), economyrate(overs, runs)
''';

In [2]:
from cricket import batsman , bowler

print('FOR BATSMAN')

runs = int(input('Enter runs:'))
matches = int(input('Enter matches:'))
balls = int(input('Enter balls:'))

print('Batsman average=' , batsman.findaverage(runs,matches))

print('Batsman strikerate=' , batsman.strikerate(runs,balls))

print('')

print('FOR BOWLER')

runs = int(input('Enter runs:'))
wickets = int(input('Enter wickets:'))
overs = int(input('Enter overs:'))

print('Bowler average=' , bowler.findavg(runs,wickets))

print('Bowler economyrate=' , bowler.economyrate(overs,runs))

FOR BATSMAN


Enter runs: 33
Enter matches: 4
Enter balls: 30


Batsman average= 8.25
Batsman strikerate= 110.00000000000001

FOR BOWLER


Enter runs: 20
Enter wickets: 3
Enter overs: 3


Bowler average= 6.666666666666667
Bowler economyrate= 6.666666666666667


In [58]:
'''
2. Write a Python function to find whether the number if prime or not.
def isPrime(num)
''';

In [59]:
def isPrime(num):
    if num > 1:
        for i in range(2, (num // 2)+1):
            if(num % i) == 0:
                print('not a prime number')
                break
            else:
                print('prime number')
    else:
        print('not a prime number')

In [60]:
isPrime(7)

prime number
prime number


In [61]:
isPrime(4)

not a prime number


In [64]:
'''
3. Write a function is_palindrome(string) that takes a string as input and returns
True if the string reads the same backward as forward (e.g., "racecar" is a palindrome).
''';

In [65]:
def is_palindrome(string):
    if string == string[::-1]:
        print(string, 'is pallindrome')
    else:
        print(string, 'is not pallindrome')

In [66]:
is_palindrome('racecar')

racecar is pallindrome


In [67]:
is_palindrome('hello')

hello is not pallindrome


In [68]:
'''
4. Write a function reverse_list(data) that takes a list as input and returns a new list
with the elements in reverse order (e.g., reverse_list([1, 2, 3]) returns [3, 2, 1]).
''';

In [69]:
data = [12,23,34,45,56,67]

def reverse_list(data):
    print(data[::-1])

In [70]:
reverse_list(data)

[67, 56, 45, 34, 23, 12]


In [71]:
'''
5. Write a function write_file(filename, content) that takes a filename and
content as input and writes the content to the specified file.
''';

In [72]:
def write_file(filename, content):
    try:
        with open(filename, 'w') as file:
            file.write(content)
        print("Successfully wrote content to", {filename})
    except IOError:
        print("Error: Could not write to", {filename})

# Example usage:
filename = "test.txt"
content = """ Helloo This is a sample text.
It will be written to a file.
Goodbye!"""
write_file(filename, content)

Successfully wrote content to {'test.txt'}


In [73]:
'''
6. Write a function copy_file(source_filename, destination_filename) that
takes the source and destination filenames as input and copies the content of the source
file to the destination file. Handle cases where the source file doesn't exist.
''';

In [74]:
def copy_file(source_filename,destination_filename):
    with open('source.txt','r') as s,open('destiantion.txt','w') as d:
        for line in s:
            d.write(line)

In [75]:
copy_file('source.txt','destination.txt')

In [76]:
'''
7. Implement a function to calculate the dot product of two NumPy arrays.
''';


In [77]:
import numpy as np
def calculate_dot_product(arr1, arr2):
    return (arr1*arr2)
arr1=np.array([[1,4,6],[5,1,78],[23,56,90]])
arr2=np.array([[23,34,45],[45,56,67],[2,9,4]])
result = calculate_dot_product(arr1, arr2)
print(result) 

[[  23  136  270]
 [ 225   56 5226]
 [  46  504  360]]


In [78]:
'''
8. Implement a GUI with a radio button selection for choosing a favorite color (e.g., red,
green, blue). Change the background color of the window based on the selected radio
button.
''';

In [79]:
import tkinter as tk
from tkinter import ttk


def change_color():
    selected_color = color_var.get()
    top.configure(bg=selected_color)

top=tk.Tk()
top.title('background color')
top.geometry('550x400') 

color_var=tk.StringVar()

colors=['red','green','blue','lavender','skyblue','pink','black']
for color in colors:
    radio_button=ttk.Radiobutton(top,text=color,value=color,variable=color_var
                                ,command=change_color)
    radio_button.pack(anchor=tk.W)


top.mainloop()
 

In [80]:
'''
9. Design a currency converter GUI. Allow users to enter an amount and select the
currencies they want to convert between (e.g., USD, EUR). Display the converted
amount in the selected currency.
''';

In [81]:
import tkinter as tk
from tkinter import ttk, messagebox
import requests

class CurrencyConverter(tk.Tk):
    def __init__(self):
        super().__init__()

        self.title("Currency Converter")
        self.geometry("400x200")

        self.amount_label = tk.Label(self, text="Amount:")
        self.amount_label.grid(row=0, column=0, padx=10, pady=10)
        
        self.amount_entry = tk.Entry(self)
        self.amount_entry.grid(row=0, column=1, padx=10, pady=10)

        self.from_currency_label = tk.Label(self, text="From:")
        self.from_currency_label.grid(row=1, column=0, padx=10, pady=10)
        
        self.from_currency_combobox = ttk.Combobox(self, values=self.get_currency_list())
        self.from_currency_combobox.grid(row=1, column=1, padx=10, pady=10)

        self.to_currency_label = tk.Label(self, text="To:")
        self.to_currency_label.grid(row=2, column=0, padx=10, pady=10)
        
        self.to_currency_combobox = ttk.Combobox(self, values=self.get_currency_list())
        self.to_currency_combobox.grid(row=2, column=1, padx=10, pady=10)

        self.convert_button = tk.Button(self, text="Convert", command=self.convert_currency)
        self.convert_button.grid(row=3, column=1, padx=10, pady=10)

        self.result_label = tk.Label(self, text="Converted Amount:")
        self.result_label.grid(row=4, column=0, padx=10, pady=10)
        
        self.result_value = tk.Label(self, text="")
        self.result_value.grid(row=4, column=1, padx=10, pady=10)

    def get_currency_list(self):
        response = requests.get('https://api.exchangerate-api.com/v4/latest/USD')
        if response.status_code == 200:
            data = response.json()
            return list(data['rates'].keys())
        else:
            messagebox.showerror("Error", "Failed to fetch currency list")
            return []

    def convert_currency(self):
        try:
            amount = float(self.amount_entry.get())
            from_currency = self.from_currency_combobox.get()
            to_currency = self.to_currency_combobox.get()

            response = requests.get(f'https://api.exchangerate-api.com/v4/latest/{from_currency}')
            if response.status_code == 200:
                data = response.json()
                rate = data['rates'][to_currency]
                converted_amount = amount * rate
                self.result_value.config(text=f"{converted_amount:.2f}")
            else:
                messagebox.showerror("Error", "Failed to fetch conversion rate")
        except ValueError:
            messagebox.showerror("Error", "Invalid amount entered")
        except Exception as e:
            messagebox.showerror("Error", str(e))

if __name__ == "__main__":
    app = CurrencyConverter()
    app.mainloop()
