In [61]:
import numpy as np

In [91]:
#create array
arr = np.array([12,23,45,56,32])

In [43]:
arr

array([12, 23, 45, 56, 32])

In [44]:
arr.dtype

dtype('int32')

In [45]:
arr = np.array([12.,23.,45.,56.,32., 66.22])

In [46]:
arr.dtype

dtype('float64')

In [47]:
arr

array([12.  , 23.  , 45.  , 56.  , 32.  , 66.22])

In [65]:
arr = np.array([12,23,45,56,32, 66.22,'pune'])

In [66]:
arr

array(['12', '23', '45', '56', '32', '66.22', 'pune'], dtype='<U32')

In [67]:
#check datatype
arr.dtype

dtype('<U32')

In [117]:
%%timeit
arr = np.array([12,23,45,56,32, 66.22,'pune'])  

4.19 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [69]:
# access element
arr[3]

'56'

In [53]:
# check shape
arr.shape

(7,)

In [54]:
arr = np.array([12,23,45,56,32])

In [55]:
# multiply
arr * 2

array([ 24,  46,  90, 112,  64])

In [56]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [58]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 2 dim array

In [70]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [71]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
arr1.shape

(4, 3)

In [74]:
# use to check dimention
arr1.ndim

2

In [75]:
# convet any dim array into 1 dim array

arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
arr1.shape

(4, 3)

In [81]:
# check how many elements are present 
arr1.size

12

In [78]:
# use to change shape
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [82]:
# use if you dont know the exact value of row
arr1.reshape(6,-1)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [84]:
# convert into 3 dim array
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [85]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [86]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
# how to access element in 2 dim array from this to this.
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [92]:
arr

array([12, 23, 45, 56, 32])

In [94]:
arr.mean()

33.6

In [95]:
arr.min()

12

In [97]:
arr = np.array([1,3,5,6,3,3,1,7])

In [99]:
# want to access unique values
np.unique(arr)

array([1, 3, 5, 6, 7])

In [100]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### linear algebra function

In [107]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
# use to find determine
np.linalg.det(arr1)

6.66133814775094e-16

In [109]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [113]:
arr2 = np.array([[1,2,3],[4,5,6],[7,12,11]])

In [114]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 12, 11]])

In [115]:
arr1 @ arr2

array([[ 30,  48,  48],
       [ 66, 105, 108],
       [102, 162, 168]])

In [116]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 96, 99]])